# Generated by Django 5.1.4 on 2025-04-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default='Họ tên đầy đủ', max_length=100)),
                ('idNumber', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10)),
                ('department', models.CharField(choices=[('Phòng Kế toán', 'Phòng Kế toán'), ('Hành chính Nhân sự', 'Hành chính Nhân sự'), ('Kinh doanh', 'Kinh doanh'), ('Điều vận', 'Điều vận')], max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('startDate', models.DateField(verbose_name='Ngày vào làm')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
