# Generated by Django 5.1.4 on 2025-04-14 13:11

import blog.function
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NganhHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=200)),
                ('introduce', ckeditor.fields.RichTextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=blog.function.RenameFileImage('logo-nganh-hang', 'name'))),
                ('status', models.BooleanField(default=True, verbose_name='Còn hoạt động')),
                ('ngay_bat_dau', models.DateField(verbose_name='Ngày bắt đầu hoạt động')),
            ],
            options={
                'verbose_name': 'Ngành hàng',
                'verbose_name_plural': 'Ngành hàng',
            },
        ),
    ]
