# Generated by Django 5.1.4 on 2025-04-15 08:29

import blog.function
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True, verbose_name='Còn hoạt động')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to=blog.function.RenameFileImage('anh_san_pham', 'name'))),
                ('nganh_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_pham_list', to='blog.nganhhang')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
    ]
