# Generated by Django 5.1.4 on 2025-04-15 11:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_sanpham'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
            options={
                'verbose_name': 'Giới thiệu',
                'verbose_name_plural': 'Giới thiệu',
            },
        ),
        migrations.AlterField(
            model_name='nganhhang',
            name='introduce',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
