# Generated by Django 5.1.4 on 2025-04-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_aboutus_alter_nganhhang_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='tiêu đề mới', max_length=200, verbose_name='Tiêu đề'),
        ),
    ]
