# Generated by Django 5.1.4 on 2025-04-15 12:07

import blog.function
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutus_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('noi_dung', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Nội dung')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('hien_thi', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=blog.function.RenameFileImage('thong_bao', 'tieu_de'))),
                ('tep_dinh_kem', models.FileField(blank=True, null=True, upload_to='thong_bao/files/', verbose_name='Tệp đính kèm')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-ngay_dang'],
            },
        ),
    ]
