# Generated by Django 5.1.4 on 2025-04-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_thongbao'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongbao',
            name='loai_bai_viet',
            field=models.CharField(choices=[('thongbao', 'Thông báo'), ('tuyendung', 'Tuyển dụng')], default='thongbao', max_length=20, verbose_name='Loại bài viết'),
        ),
    ]
